tempchk	.fill	1		;
unsolvd	lda	#0		;
	rts			;
checkok	bit	state+0		;
	bpl	unsolvd		;
	bvs	unsolvd		;
	bit	state+4		;
	bpl	unsolvd		;
	bvs	unsolvd		;
	bit	state+8		;
	bpl	unsolvd		;
	bvs	unsolvd		;
	bit	state+$c	;
	bpl	unsolvd		;
	bvs	unsolvd		;
	bit	state+3		;
	bpl	unsolvd		;
	bvc	unsolvd		;
	bit	state+7		;
	bpl	unsolvd		;
	bvc	unsolvd		;
	bit	state+$b	;
	bpl	unsolvd		;
	bvc	unsolvd		;
	bit	state+$f	;
	bpl	unsolvd		;
	bvc	unsolvd		;
	lda	state+0		;
	and	#$3f		;
	sta	tempchk		;
	lda	state+0+1	;
	and	#$3f		;
	cmp	tempchk		;
	beq	+		;
	
	lda	#1		;
	rts			;
